config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'
  get "create_acc/index"
  get "login_page/index"
  get "welcome/index"

  resources :houses

  root "welcome#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# Base ApplicationRecord Class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" },  default_url: "/:style/missing.png", validate_media_type: false
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/create_acc_controller.rb
class CreateAccController < ApplicationController
  def index
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def show
    @house = House.find(params[:id])
  end

  def new
    @house = House.new
  end

  def edit
    @house = House.find(params[:id])
  end

  def create
    @house = House.create!(house_params)

    if @house.save
      redirect_to @house
    else
      render 'new'
    end
  end

  def update
    @house = House.find(params[:id])

    if @house.update(house_params)
      redirect_to @house
    else
      render 'edit'
    end
  end

  def destroy
  @house = House.find(params[:id])
  @house.destroy

  redirect_to houses_path
end

  private
  def house_params
    params.require(:house).permit(:description, :monthly_rent, :image, :owner,
                                  :num_rooms, :num_bathrooms, :pets)
  end
end

app/controllers/login_page_controller.rb
class LoginPageController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_acc_helper.rb
module CreateAccHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/login_page_helper.rb
module LoginPageHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/create_acc/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Create Account</title>
  <meta name="csrf-param" content="authenticity_token" />
  <meta name="csrf-token" content="lj4oCenB9Q6D3BJCvDBkWhvQFjO5GlleAl+OAgzUUJaMPkF9gEF3a4qpPfqa4NCa7+msO5L+WI57d8oWQuYA+Q==" />


  <link rel="stylesheet" media="all" href="/assets/create_acc.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="reload" />
  <link rel="stylesheet" media="all" href="/assets/homepage.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="reload" />
  <link rel="stylesheet" media="all" href="/assets/login_page.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="reload" />
  <link rel="stylesheet" media="all" href="/assets/welcome.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="reload" />
  <link rel="stylesheet" media="all" href="/assets/application.self-f0d704deea029cf000697e2c0181ec173a1b474645466ed843eb5ee7bb215794.css?body=1" data-turbolinks-track="reload" />
  <script src="/packs/js/application-05bc83490fcade04d051.js" data-turbolinks-track="reload"></script>
</head>

<body>
  <div id="clearance" class="sign-up">
    <h2>Sign up</h2>

    <form class="new_user" id="new_user" action="/users" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="pfDcAuGxyz+7BCB9ScuvyHHiDzgXU3DcYY5JkMGFcSqG+1O4q31viUshzKHQbTMUbE3CZ6WpnPwtsFBYoslgjg==" />
      <div class="text-field">
        <label for="user_email">Email</label>
        <input type="email" name="user[email]" id="user_email" />
      </div>

      <div class="password-field">
        <label for="user_password">Password</label>
        <input type="password" name="user[password]" id="user_password" />
      </div>


      <div class="submit-field">
        <input type="submit" name="commit" value="Sign up" data-disable-with="Sign up" />
      </div>

      <div class="other-links">
        <a href="/sign_in">Sign in</a>
      </div>
    </form></div>

  </body>
  </html>

app/views/homepage/index.html.erb
<h1>Homepage#index</h1>
<p>Find me in app/views/homepage/index.html.erb</p>

app/views/houses/edit.html.erb
<style>
  h1{
    text-align: center;
  }
  p{
    text-align: center;
  }
</style>

<%= link_to ("Return to homepage"), root_path, class: "return-link" %>


<h1>Edit House</h1>

<%= form_with(model: @house, local: true) do |form| %>

  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@house.errors.count, "error") %> prohibited
        this house from being saved:
      </h2>
      <ul>
        <% @house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </p>

    <p>
      <%= form.label :description %><br>
      <%= form.text_field :description %>
    </p>

    <p>
      <%= form.label :monthly_rent %><br>
      <%= form.text_area :monthly_rent %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>

app/views/houses/index.html.erb
<style>
  h1{
    text-align: center;
  }
  table{
    margin-left: auto;
    margin-right: auto;
  }
  th {
  padding: 10px;
}
  .description-limit{
    max-width: 40px;
   text-overflow: ellipsis;
   overflow: hidden;
   white-space: nowrap;
  }
  .return-link{
    margin-left: 20px;
  }
  a{
    color: black;
  }
  a:hover{
    color: blue;
  }
  label{
    text-align: center;
    margin-left: 900px;
  }
  .search-container{
    margin-left: 510px;
  }
</style>

<%= link_to ("Return to homepage"), root_path, class: "return-link" %>

<h1>Listing Houses</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Monthly Rent</th>
    <th>Bedrooms</th>
    <th>Bathrooms</th>
    <th>Pets</th>
    <th></th> 
  </tr>

  <% @houses.each do |house| %>
    <tr>
      <td class="description-limit"><%= house.description %></td>
      <td><%= house.monthly_rent %></td>
      <td><%= house.num_rooms %></td>
      <td><%= house.num_bathrooms %></td>
      <td><%= house.pets %></td>
      <td><%= link_to 'Show', house_path(house) %></td>
      <% if current_user.email == house.owner %>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Delete', house_path(house),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>

</table>

app/views/houses/new.html.erb
<style>
  .new-house {
    text-align: center;

  }
  .return-link{
    margin-left: 20px;
  }
</style>
<%= link_to ("Return to homepage"), root_path, class: "return-link" %>

<div class="new-house">
<h1>Add New House</h1>
<%= form_for @house, html: { multipart: true } do |form| %>

<%= form.hidden_field :owner, required: true, value:current_user.email  %>


<p>
  <%= form.label :image %><br><br>
  <%= form.file_field :image %>
</p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :monthly_rent %><br>
    <%= form.text_area :monthly_rent %>
  </p>

  <p>
    <%= form.label :num_rooms %><br>
    <%= form.text_area :num_rooms %>
  </p>

  <p>
    <%= form.label :num_bathrooms %><br>
    <%= form.text_area :num_bathrooms %>
  </p>

  <p>
    <%= form.label :pets %><br>
    <%= form.text_field :pets %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

</div>

app/views/houses/show.html.erb
<style>
    .show-house {
      text-align: center;
      margin-top: 100px;
    }
    .return-link{
      margin-left: 20px;
    }
</style>

<%= link_to ("Return to homepage"), root_path, class: "return-link" %>

<div class="show-house">

  <%= image_tag @house.image.url(:medium) %>

  <p>
    <strong>Description:</strong>
    <%= @house.description %>
  </p>

  <p>
    <strong>Monthly Rent:</strong>
    <%= @house.monthly_rent %>
  </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spike</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <style>
    html{
      background-image: radial-gradient(#FFFFFF, #808285, #d1d3d4);
      background-repeat: no-repeat;
      height: 100%;
     }
     h3{
       color: black;
       margin-left: 20px;
      }
      a.profile_link{
        padding: 0px;
        font-size: 20px;
        border-style: none;
        margin-left: 0px;
        text-decoration: none;
      }
      .sign_out_button {
        margin-top: 20px;
      }
      a:hover{
        color: blue;
      }
  </style>
</head>

<body>
  <header>
    <% if signed_in? %>
      <h3>User Signed On: <%= current_user.email %><h3>
      <%= link_to 'My Profile', profile_index_path, :class => "profile_link" %>
      <%= button_to 'Sign out', sign_out_path, method: :delete, :class => "sign_out_button" %>
    <% else %>
      <h3>Unregistered User<h3>
    <% end %>
  </header>

  <section>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </section>
</body>
</html>

app/views/login_page/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spike</title>

  <style>
    .text-field {
      margin-top: 50px;
    }
  </style>
</head>

<body>
  <header>
  </header>

  <section>
    <div id="flash">
    </div>
    <div id="clearance" class="sign-in">
      <h2>Sign in</h2>

      <form action="/session" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="7pJqZVhEEX5j6uFm8odzV8eT/1tFTto4An8qjFyBlOVwYfnSvgPfh5XlIBvhINw7x1uRA6pNY1BZyZdfABdeyQ==" />
        <div align="center" class="text-field">
          <label for="session_email">Email</label>
          <input type="email" name="session[email]" id="session_email" />
        </div>

        <div class="password-field">
          <label for="session_password">Password</label>
          <input type="password" name="session[password]" id="session_password" />
        </div>

        <div class="submit-field">
          <input type="submit" name="commit" value="Sign in" data-disable-with="Sign in" />
        </div>

        <div class="other-links">
          <a href="/sign_up">Sign up</a>
        </div>
      </form>

    </div>

  </section>
</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<style>
  #clearance {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    text-align: center;
    min-height: 75vh;
  }
  .text-field {
    margin: 20px;
  }
  .password-field {
    margin: 30px;
    padding-right: 20px;
  }

  .submit-field {
    margin-bottom: 20px;
  }
  .other-links {
    text-align: center;
  }
  .homepage-field{
    margin-top: 20px;
  }

</style>

<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
      <%= link_to ("Return to Homepage"), root_path, {:style=>'margin-left:20px'} %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title>Welcome Page</title>
  <style>
    html{
      background-image: radial-gradient(#FFFFFF, #808285, #d1d3d4);
    }
    body{

    }
    h1 {
      text-align: center;
      font-size: 75px;
      color: #c2011b;
    }
    a{
      color: black;
      padding: 30px;
      font-size: 40px;
      border-style: solid;
      margin-left: 30px;
    }
    div{
      margin-top: 100px;
    }

  </style>
</head>

<body>

  <h1>Welcome to MyRoommate Finder!</h1>

  <div style="text-align: center">
    <%= link_to 'Login', sign_in_path %>
    <%= link_to 'Create Account', sign_up_path %>
    <%= link_to 'Listing of All Houses', controller: 'houses' %>
    <% if signed_in? %>
    <div><%= link_to 'Add House to Listing', new_house_path %></div>
    <% end %>
  </div>
</body>
</html>